version: '3.8'

services:
  app1:
    build: .
    ports:
      - "3000"
    environment:
      - PORT=3000
      - SERVER_ID=app1

  app2:
    build: .
    ports:
      - "3001"
    environment:
      - PORT=3001
      - SERVER_ID=app2

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
